app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(add = "click")
app$setInputs(add = "click")
app$setInputs(add = "click")
app$setInputs(tabs = "Dynamic  3")
app$setInputs(add = "click")
app$setInputs(add = "click")
app$setInputs(add = "click")
app$setInputs(tabs = "Dynamic  6")
app$setInputs(add = "click")
app$setInputs(add = "click")
app$setInputs(add = "click")
app$setInputs(tabs = "Dynamic  9")
app$snapshot()
